# Generated by Django 2.1.1 on 2018-09-29 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
                ('description', models.TextField(blank=True, max_length=10000, null=True, verbose_name='описание')),
                ('composition', models.TextField(blank=True, max_length=10000, null=True, verbose_name='состав')),
                ('bar_code', models.CharField(max_length=13, unique=True, verbose_name='штрих-код')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images', verbose_name='картинка')),
            ],
            options={
                'verbose_name': 'продукт',
                'verbose_name_plural': 'продукты',
            },
        ),
        migrations.CreateModel(
            name='UserProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_to', models.DateField(verbose_name='годен до')),
                ('consumed', models.BooleanField(default=False, verbose_name='сожрано?')),
                ('created_at', models.DateTimeField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.Product', verbose_name='продукт')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'продукт пользователя',
                'verbose_name_plural': 'продукты пользователя',
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['bar_code'], name='product_pro_bar_cod_f1360d_idx'),
        ),
    ]
