# Generated by Django 2.1.1 on 2018-09-29 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='composition',
            field=models.TextField(blank=True, max_length=40000, null=True, verbose_name='состав'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, max_length=40000, null=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=4000, verbose_name='название'),
        ),
    ]
